### ISSUE TITLE
Configuration could not be read

### ISSUE THREAD

**Issue by SinisterSpatula** [GauriSpears/guacamole-noauth#1]
Tried to set it up to use noauth extension with the 1.5.5 guacamole docker container and getting an error message:
```
guacamole  | 22:07:49.274 [http-nio-8080-exec-3] WARN  o.a.g.e.AuthenticationProviderFacade - The "noauth" authentication provider has encountered an internal error which will halt the authentication process. If this is unexpected or you are the developer of this authentication provider, you may wish to enable debug-level logging. If this is expected and you wish to ignore such failures in the future, please set "skip-if-unavailable: noauth" within your guacamole.properties.
guacamole  | 22:07:49.275 [http-nio-8080-exec-3] ERROR o.a.g.rest.RESTExceptionMapper - Request could not be processed: Configuration could not be read.
```

![Image](https://github.com/user-attachments/assets/003dd5f1-3798-4cbf-a55e-c5712f971efe)

### compose.yaml
```yaml
services:
  guacamole:
    image: guacamole/guacamole:1.5.5
    container_name: guacamole
    restart: unless-stopped
    volumes:
      - ./config:/etc/guacamole
    environment:
      - GUACAMOLE_HOME=/etc/guacamole
      - MY_PC_PASSWORD=${MY_PC_PASSWORD}
      - UNRAID_VM_PASSWORD=${UNRAID_VM_PASSWORD}
      - GUACD_HOSTNAME=guacd
      - GUACD_PORT=4822
    networks:
      backend: null
    depends_on:
      - guacd
  guacd:
    image: guacamole/guacd:1.5.5
    container_name: guacd
    restart: unless-stopped
    networks:
      backend: null
networks:
  backend:
    external: true
```
### guacamole.properties
```yaml
auth-provider: net.sourceforge.guacamole.net.auth.noauth.NoAuthenticationProvider
noauth-config: /home/guacamole/.guacamole/noauth-config.xml
```

### nauth-config.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configs>
    <config name="My-PC" protocol="rdp">
        <param name="hostname" value="my-pc.home.arpa"/>
        <param name="port" value="3389"/>
        <param name="username" value="myusername"/>
        <param name="password" value="${MY_PC_PASSWORD}"/>
        <param name="ignore-cert" value="true"/>
    </config>
    <config name="Server2" protocol="rdp">
        <param name="hostname" value="unraid-vm.home.arpa"/>
        <param name="port" value="3389"/>
        <param name="username" value="unraid"/>
        <param name="password" value="${UNRAID_VM_PASSWORD}"/>
        <param name="ignore-cert" value="true"/>
    </config>
</configs>
```

I've tried both `noauth-config: /home/guacamole/.guacamole/noauth-config.xml` and `/etc/guacamole/noauth-config.xml` and both result in the same issue.

I'm sure I'm just doing something dumb but have not been able to figure it out.

I can successfully cat out the noauth-config.xml from inside the container (docker exec -it guacamole /bin/bash).  The one in /home/guacamole/.guacamole/ belongs to user guacamole and the one in /etc/guacamole belongs to root, but neither one seem to work.  I also tried replacing noauth-config.xml with the example one, still same.
